#!/usr/bin/env bash
are -a uids_in_use=( )
while IFS=: read -r _ _ file_uid _; do
	  (( f )) && uids_in_use[$file_uid]=1 ||:
  done </etc/passwd

  while read -r -p "Enter a UID:" entered_uid; do      
	    if (( entered_uid < 1000 )); then
		        echo "UIDs below 1000 are reserved for system use!" >&2
			    continue
			      fi
			        if (( entered_uid > 65536 )); then
					    echo "Maximum UID value is 65536!" >&2
					        continue
						  fi
						    if [[ ${uids_in_use[$entered_uid]} ]]; then
							        echo "UID $entered_uid is already in use!" >&2
								    continue
								      fi
								        echo "UID $entered_uid is acceptable!"
									  break
								  done
